### ISSUE TITLE
CocoaPods points to an outdated version

### ISSUE THREAD

**Issue by alonre** [kissmetrics/KISSmetrics-iOS-SDK#25]
My build fails on "BitCode" phase.
That was (allegedly) solved in 2.3.0 (Sep 2016)
CocoaPods has 2.2.0 (Sep 2014).

Can you please update CocoaPods to point to 2.3.0?

**Comment by percyhanna** [comment]
I've published 2.3.1 to CocoaPods. Thanks.

**Comment by alonre** [comment]
Thanks!
