### ISSUE TITLE
Link error using KISSMetrics Cocoapod

### ISSUE THREAD

**Issue by djfitz** [kissmetrics/KISSmetrics-iOS-SDK#26]
I'm using the Cocoapod version of the KISSMetrics SDK framework.

I haven't update my cocoapod for my project in a while. Now that I've updated, I get the following link error:

ld: framework not found KISSmetricsSDK

Apparently the framework name was changed which seems to be causing this error. But I've done everything I could to reset my project to use this new version of the pod.
• Clean build folder in project.
• Remove all Derived Data
• Remove Podfile.lock
• Remove generated workspace
• Run 'pod update'

The pod builds fine but my app won't link.

Any help would be appreciated.

**Comment by djfitz** [comment]
I figured it out, there was another framework flags setting I missed.

**Comment by percyhanna** [comment]
Glad you figured it out. Let us know if you run into any other problems.
